# Generated by Django 4.2.7 on 2024-01-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gpio',
            fields=[
                ('gpio_number', models.IntegerField(primary_key=True, serialize=False)),
                ('gpio_description', models.CharField(max_length=100)),
                ('gpio_function', models.CharField(max_length=10)),
                ('gpio_state', models.CharField(default='-', max_length=10)),
            ],
        ),
    ]
